version: '3.1'

services:
  tb:
    image: "thingsboard/application:2.0.3"
    ports:
      - "8081:8080"
      - "18832:1883"
      - "5684:5683/udp"
    env_file:
      - tb.env
    environment:
      - ADD_SCHEMA_AND_SYSTEM_DATA=true
      - ADD_DEMO_DATA=true
    #volumes:
    #  - ${PWD}/certificate:/etc/thingsboard/conf/certificate
    #  - ${PWD}/certificate/mqttserver.jks:/etc/thingsboard/conf/certificate/mqttserver.jks
    entrypoint: /run-application.sh
  cassandra:
    image: "cassandra:3.11.4"
    ports:
      - "9042"
      - "9160"
    volumes:
      - "${CASSANDRA_DATA_DIR}:/var/lib/cassandra"
